package com.example.PriceComparator.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.List;

/**
 * This is used for storing the shopping list generated by the products in the basket. Shopping lists are based only
 * on one shop.
 * The total price for the products in this list is computed.
 */
@Entity
@Table(name = "shopping_list")
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ShoppingList {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    private User user;

    private String name;

    @ManyToOne
    private Store store;

    @OneToMany(mappedBy = "shoppingList", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ShoppingListItem> items;

    private BigDecimal totalPrice;
}
